package search

import (
	"math"

	"github.com/Droanox/ChessEngineAI/src/board"
	"github.com/Droanox/ChessEngineAI/src/engine"
)

func negamax(alpha int, beta int, depth int, cb *board.ChessBoard) int {
	// pvFound is used to determine if the principal variation was found
	var pvFound bool = false

	// pvLength[board.Ply+1] is used to store the length of the principal variation
	pvLength[board.Ply+1] = board.Ply + 1

	// when the depth is 0, we call quiescence search to search for captures
	if depth == 0 {
		return quiescence(alpha, beta, cb)
	}

	// If the maximum ply is reached, we evaluate the position and return the score
	// instead of searching further as it'll break the search
	if board.Ply > board.MaxPly {
		return engine.Eval(*cb)
	}

	nodes++

	// check if the side to move is in check
	// if so, we increase the depth by 1 to search deeper
	var isChecked bool
	if board.SideToMove == board.White {
		isChecked = cb.IsSquareAttackedBySide(board.BitScanForward(cb.WhiteKing), board.Black)
	} else {
		isChecked = cb.IsSquareAttackedBySide(board.BitScanForward(cb.BlackKing), board.White)
	}
	if isChecked {
		depth++
	}

	// legalMovesNum is used to count the number of legal moves
	var legalMovesNum int

	// movelist is used to store the list of moves generated by the GenerateMoves function
	var moveList = []board.Move{}
	// generate all the moves
	cb.GenerateMoves(&moveList)

	// if the principal variation was found in the previous iteration, we score the principal variation
	// otherwise, we score all the moves
	if pvFollowed {
		scorePV(&moveList)
	} else {
		scoreMoves(&moveList)
	}

	for i := 0; i < len(moveList); i++ {
		pickMove(&moveList, i)

		if !cb.MakeMove(moveList[i]) {
			continue
		}

		// increment legal moves for checkmate and stalemate detection
		legalMovesNum++

		// store the score
		var score int

		// Principal Variation Search (PVS)
		// https://www.chessprogramming.org/Principal_Variation_Search
		if pvFound {
			score = -negamax(-alpha-1, -alpha, depth-1, cb)
			if (score > alpha) && (score < beta) {
				score = -negamax(-beta, -score, depth-1, cb)
			}
		} else {
			score = -negamax(-beta, -alpha, depth-1, cb)
		}

		// unmake the move
		cb.MakeBoard()

		// fails high
		if score >= beta {
			if (moveList[i].GetMoveFlags() & board.MoveCaptures) == 0 {
				killerMoves[1][board.Ply+1] = killerMoves[0][board.Ply+1]
				killerMoves[0][board.Ply+1] = moveList[i]
			}

			return beta
		}
		// found a better move
		if score > alpha {
			if (moveList[i].GetMoveFlags() & board.MoveCaptures) == 0 {
				historyMoves[moveList[i].GetMoveStartPiece()+(6*board.SideToMove)-1][moveList[i].GetMoveEnd()] += depth
			}

			alpha = score

			pvFound = true

			pvTable[board.Ply+1][board.Ply+1] = moveList[i]

			for j := board.Ply + 2; j < pvLength[board.Ply+2]; j++ {
				pvTable[board.Ply+1][j] = pvTable[board.Ply+2][j]
			}

			pvLength[board.Ply+1] = pvLength[board.Ply+2]
		}
	}

	// check for checkmate and stalemate
	if legalMovesNum == 0 {
		if isChecked {
			return (math.MinInt32 + 10) + board.Ply
		} else {
			return 0
		}
	}

	// fails low
	return alpha
}
